kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      volumes:
        - name: config
          configMap:
            name: config-{{ .Release.Name }}
      containers:
        - name: server
          image: "{{ .Values.server.registry }}:{{ .Values.server.tag }}"
          imagePullPolicy: {{ .Values.server.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: config