apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Release.Name }}-nginx