kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: clash-proxy-operator
          image: "{{ .Values.operator.registry }}:{{ .Values.operator.tag }}"
          args:
            - --enable-leader-election
          env:
            - name: CLASH_PROXY_PUBLIC_IPS
              value: {{ .Values.expose.publicIPs | join "," }}
            - name: CLASH_PROXY_CONFIG_MAP_NAME
              value: config-{{ .Release.Name }}
            - name: WATCH_NAMESPACE
              value: {{ .Release.Namespace }}
          imagePullPolicy: {{ .Values.operator.pullPolicy }}
