apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - 'apps'
    resources:
      - 'deployments'
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - 'configmaps'
  - verbs:
      - '*'
    apiGroups:
      - 'coordination.k8s.io'
    resources:
      - 'leases'