kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name:  role-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
